
services:
  edge:
    image: quay.io/asterisk/asterisk:20
    container_name: voiceai-edge
    network_mode: host
    environment:
      - ASTERISK_UID=1000
      - ASTERISK_GID=1000
    volumes:
      - ./services/edge/etc/asterisk:/etc/asterisk
      - ./services/edge/var/lib/asterisk:/var/lib/asterisk
    restart: unless-stopped

  orchestrator:
    build:
      context: ./services/orchestrator
    container_name: voiceai-orchestrator
    ports:
      - "8080:8080"
    env_file:
      - ./config/.env
    volumes:
      - ./flows:/app/flows:ro
    depends_on:
      - edge
    restart: unless-stopped
